---
detectors:
  NestedIterators:
    exclude:
      - 'Rambling::Trie#create' # inner iteration goes through each word in given file
      - 'Rambling::Trie::Container#words_within_root' # inner iteration does a match of each prefix
      - 'Rambling::Trie::Enumerable#each' # inner iteration goes through each word in children_tree

  UnusedParameters:
    exclude:
      # Rambling::Trie::Nodes::Node has some abstract methods
      - 'Rambling::Trie::Nodes::Node#children_match_prefix'
      - 'Rambling::Trie::Nodes::Node#closest_node'
      - 'Rambling::Trie::Nodes::Node#partial_word_chars?'
      - 'Rambling::Trie::Nodes::Node#word_chars?'
      # Rambling::Trie::Readers::Reader is an abstract class
      - 'Rambling::Trie::Readers::Reader#each_word'
      # Rambling::Trie::Serializers::Serializer is an abstract class
      - 'Rambling::Trie::Serializers::Serializer#dump'
      - 'Rambling::Trie::Serializers::Serializer#load'

  UtilityFunction:
    public_methods_only: true
    exclude:
      # Rambling::Trie::Serializers::File are intentionally using ::File methods
      - 'Rambling::Trie::Serializers::File#dump'
      - 'Rambling::Trie::Serializers::File#load'
