module Rambling
  module Trie
    module Comparable[TValue < _Inspect]
      def ==: (Nodes::Node[TValue]) -> bool

      private

      # abstract methods

      def letter: -> Symbol

      def terminal?: -> bool

      def children_tree: -> Hash[Symbol, Nodes::Node[TValue]]
    end
  end
end
