module Rambling
  module Trie
    module Comparable
      def ==: (Nodes::Node) -> bool

      private

      # abstract methods

      def letter: -> Symbol

      def terminal?: -> bool

      def children_tree: -> Hash[Symbol, Nodes::Node]
    end
  end
end
