module Rambling
  module Trie
    module Compressible[TValue < _Inspect]
      def compressible?: -> bool

      private

      # abstract methods

      def root?: -> bool

      def terminal?: -> bool

      def children_tree: -> Hash[Symbol, Nodes::Node[TValue]]
    end
  end
end
