module Rambling
  module Trie
    class Container[TValue < _Inspect]
      include ::Enumerable[String]

      @compressor: Compressor[TValue]

      attr_reader root: Nodes::Node[TValue]

      def initialize: (Nodes::Node[TValue], Compressor[TValue]) ?{ (Container[TValue]) -> void } -> void

      def add: (String, ?TValue?) -> Nodes::Node[TValue]

      def concat: (Array[String], ?Array[TValue?]?) -> Array[Nodes::Node[TValue]]

      def compress!: -> Container[TValue]

      def compress: -> Container[TValue]

      def each: { (String) -> void } -> (Enumerator[String, void] | Enumerable[TValue])

      def partial_word?: (String) -> bool

      def push: (*String) -> Array[Nodes::Node[TValue]]

      def word?: (String) -> bool

      def scan: (String) -> Array[String]

      def words_within: (String) -> Array[String]

      def words_within?: (String) -> bool

      def ==: (Container[TValue]) -> bool

      def []: (Symbol) -> Nodes::Node[TValue]

      def children: -> Array[Nodes::Node[TValue]]

      def children_tree: -> Hash[Symbol, Nodes::Node[TValue]]

      def compressed?: -> bool

      def to_a: -> Array[String]

      def key?: (Symbol) -> bool

      def size: -> Numeric

      alias include? word?
      alias match? partial_word?
      alias words? scan
      alias << add
      alias has_key? key?
      alias has_letter? key?

      private

      attr_reader compressor: Compressor[TValue]
      attr_writer root: Nodes::Node[TValue]

      def words_within_root: (String) ?{ (String) -> void } -> Enumerator[String, void]

      def compress_root: -> Nodes::Compressed[TValue]

      def reversed_char_symbols: (String) -> Array[Symbol]
    end
  end
end
