module Rambling
  module Trie
    module Stringifyable[TValue < _Inspect]
      def as_word: -> String

      def to_s: -> String

      private

      # abstract methods

      def letter: -> Symbol

      def terminal?: -> bool

      def parent: -> Nodes::Node[TValue]?

      def children_tree: -> Hash[Symbol, Nodes::Node[TValue]]
    end
  end
end
