module Rambling
  module Trie
    module Nodes
      class Compressed < Node
        def add: (Array[Symbol]) -> Node

        def compressed?: -> bool

        private

        def partial_word_chars?: (Array[String | Symbol]) -> bool

        def word_chars?: (Array[String | Symbol]) -> bool

        def closest_node: (Array[String | Symbol]) -> Node

        def children_match_prefix: (Array[String | Symbol]) -> Enumerator[String, void]
      end
    end
  end
end
