module Zip
  class File
    CREATE: bool

    def self.open: [TContent] (String, ?bool?) { (File) -> TContent } -> TContent

    def entries: -> Array[Entry]

    def add: (String, String) -> void
  end
end