module Rambling
  module Trie
    module Serializers
      class Marshal < Serializer[Nodes::Node]
        @serializer: Serializer[String]

        private

        attr_reader serializer: Serializer[String]
      end
    end
  end
end
