module Rambling
  module Trie
    module Serializers
      class Marshal[TValue < _Inspect] < Serializer[Nodes::Node[TValue]]
        @serializer: Serializer[String]

        private

        attr_reader serializer: Serializer[String]
      end
    end
  end
end
