module Rambling
  module Trie
    module Serializers
      class Zip[TValue < _Inspect] < Serializer[Nodes::Node[TValue]]
        @properties: Configuration::Properties[TValue]

        def initialize: (Configuration::Properties[TValue]) -> void

        private

        attr_reader properties: Configuration::Properties[TValue]

        def serializers: -> Configuration::ProviderCollection[Serializer[Nodes::Node[TValue]]]

        def tmp_path: -> String

        def path: (String) -> String
      end
    end
  end
end
