name: Ruby

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Lint
        run: bundle exec rubocop
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 3.2.2
          - 3.2.1
          - 3.2.0
          - 3.1.4
          - 3.1.3
          - 3.1.2
          - 3.1.1
          - 3.1.0
          - 3.0.6
          - 3.0.5
          - 3.0.4
          - 3.0.3
          - 3.0.2
          - 3.0.1
          - 3.0.0
          - 2.7.8
          - 2.7.7
          - 2.7.6
          - 2.7.5
          - 2.7.4
          - 2.7.3
          - 2.7.2
          - 2.7.1
          - 2.7.0
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Run tests and report test coverage
        run: COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }} bundle exec rspec
